export const POST_CUSTOM_PRICING_REQUESTED = 'POST_CUSTOM_PRICING_REQUESTED';
export const POST_CUSTOM_PRICING_RECEIVED = 'POST_CUSTOM_PRICING_RECEIVED';
export const POST_CUSTOM_PRICING_FAILED = 'POST_CUSTOM_PRICING_FAILED';
